# Generated by Django 3.0.2 on 2020-02-03 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Non-Title', max_length=100)),
                ('description', models.CharField(max_length=500, null=True)),
                ('name', models.CharField(default='Non-Name', max_length=150)),
                ('sureName', models.CharField(max_length=150, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('video', models.FileField(upload_to='videos')),
                ('created_At', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contests.Contest')),
            ],
        ),
    ]
