# Generated by Django 3.0.2 on 2020-02-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_auto_20200208_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='state',
            field=models.CharField(default='PENDING', max_length=15),
        ),
    ]
