# Generated by Django 3.0.2 on 2020-02-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_video_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created_At',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
