# Generated by Django 3.0.2 on 2020-02-03 03:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Non Name', max_length=150)),
                ('startDate', models.DateTimeField(default=datetime.datetime(2020, 2, 2, 22, 30, 45, 296895))),
                ('endDate', models.DateTimeField(default=datetime.datetime(2020, 2, 2, 22, 30, 45, 296895))),
                ('path', models.CharField(default='Non Prize', max_length=8)),
                ('prize', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logo', models.FileField(null=True, upload_to='logos')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
