# Generated by Django 2.2.5 on 2020-02-08 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 8, 21, 3, 48, 637007)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='path',
            field=models.CharField(default='Non Path', max_length=8),
        ),
        migrations.AlterField(
            model_name='contest',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 8, 21, 3, 48, 636966)),
        ),
    ]
