# Generated by Django 3.0.2 on 2020-02-10 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20200208_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 9, 19, 18, 7, 653235)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 9, 19, 18, 7, 653235)),
        ),
    ]
